# Literature review {#literature-review}

A variety of state space-models have been applied in the context of the log linear approximation of the present-value formulation. In particular, assuming stationarity of the PD and hence the existence of the long-term mean, @binsbergen_paper used a linear state-space model for modeling state processes for the expected return and expected dividend growth. Furthermore, @tvp_kf added the possibility of time-varying parameters to this application.

However, as mentioned, this thesis will focus on the results from @h2_paper where the PD has been modeled as a nonstationary process. There the latent mean has been characterized as a random walk and as an autoregressive process of order one. The results indicate that the random walk model is superior measured by typical model comparison figures as the Bayesian information criterion. 

Furthermore, parameter inference has been carried out by maximizing the likelihood using the Nelder–Mead optimization method [@nelder_mead]. Using this approach, due to the stochasticity of the likelihood function, the Hessian cannot be approximated reliably and therefore confidence intervals for the parameters based on the observed Fisher information cannot be retrieved. 

@h2_paper2 applied a similar nonlinear state-space model, however for the price-to-rent ratio of the US housing market using the Federal Housing Finance Agency housing price index. Parameter inference has been conducted using multiple runs of a grid search procedure. Again, uncertainty quantification of parameter estimates is not feasible within this setup.

This master's thesis will therefore try to extend the summarized approaches by applying the Bayesian PMMH approach. Hence, after having obtained an approximation of the posterior distribution, it is possible to retrieve credible intervals for the parameters of interest and pointwise credible intervals for the filtered state process.

Besides that, @h2_paper used the filtered latent mean for studying the effect of possible determinants within a cointegration analysis. This analysis has shown that a cointegration relationship between the latent mean of the PD, consumption risk, the middle-aged to young ratio and the proportion of firms with traditional dividend payout policy exists. Hence, adding to these results, further macroeconomic variables will be inspected via a cointegration analysis and by estimating a state process extension containing exogenous covariates directly.

In particular, the effect of monetary policy on the latent mean of the PD will be inspected. Empirical evidence has shown that monetary policy, especially quantitative easing, affects asset prices [@monetary_policy_1; @monetary_policy_2; @monetary_policy_asset_prices]. Therefore, the effects of changes in real M1 money supply and the effective federal funds rate will be investigated. The real M1 money supply represents the most liquid portion of money supply and it captures the amount of physical currency and money held in checking accounts. Furthermore, the effective federal funds rate represents the target interest rate at which commercial banks lend and borrow money from each other overnight.

Moreover, the possible link between economic growth and increasing stock prices will be checked as well, even though research indicates that this relationship is questionable [@economic_growth].

As mentioned, nonlinear state-space models require fast running software due to complex Monte Carlo procedures being employed. For the \texttt{R} programming language three possible and freely available packages can be used for modeling nonlinear state-space models: \texttt{Biips} [@biips_paper], \texttt{NIMBLE} [@nimble_paper] and \texttt{pomp} [@pomp_article]. The first two are extensions of the BUGS software for Bayesian analysis using Markov chain Monte Carlo (MCMC), see [@bugs_paper]. 

For this master's thesis the \texttt{pomp} package has been used. Contrary to the other two, it contains simulation based algorithms for both Bayesian and likelihood based procedures. Furthermore, its plug and play architecture makes it easy to develop and test new models. Moreover, for speeding up the inferential procedures, it allows to program lower level code in \texttt{C}. Besides that, within this project, all applications have been run on a powerful cloud server, parallel computing has been used and some key code components have been written in \texttt{C} and \texttt{C++} using \texttt{Rcpp} [@rcpp] and \texttt{RcppArmadillo} [@rcpparmadillo].
