# Conclusion {#conclusion}

The basic structure of partially observed Markov processes and corresponding numerical procedures for inference have been described briefly. Furthermore, a simulation study has been conducted and the results of likelihood based and Bayesian approaches for parameter and latent state estimation have been presented. Different prior setups have been tested and a general superiority of either the likelihood or the Bayesian approach could not be identified. However, the advantage of the Bayesian approach for providing uncertainty quantification for parameter and latent state estimates has been used for the empirical application. 

Based on the log linear approximation of the present-value formulation presented by @campbell_shiller_paper, a nonlinear state-space model has been derived as done by @h2_paper. Firstly, a random walk state process has been used for the latent mean of the PD. The PMMH approach has been successfully applied for estimating the parameter and latent state and for providing the corresponding uncertainty quantification.

Similar to the steps applied by @h2_paper, a cointegration analysis has been conducted by including macroeconomic variables characterizing monetary policy effects and economic growth. However, a cointegration relationship could not be detected. An additional model containing the middle-aged to young ratio and the log real M1 money supply has been tested. The random walk state setup and the state model containing covariates follow similar paths. However, the model comparison results showed that the model with a random walk state process is superior.

All in all, the particle marginal Metropolis Hastings approach has been successfully applied to the context of a nonlinear state-space model for the log linear approximation of the present-value formulation.

As a possible outlook, further advances in MCMC approaches for nonlinear partially observed Markov processes have been developed. Being able to generate proposals that are more likely to be accepted whilst exploring the parameter space efficiently is possible by adding posterior gradient estimates to the MCMC approaches. This would improve analyzing more complicated models with further parameters significantly. Additionally, another interesting application would be the likelihood based iterated filtering procedure and the corresponding confidence interval estimation using the Monte Carlo adjusted profile algorithm.
